config/routes.rb
Rails.application.routes.draw do
  resources :companies
  root 'companies#index'
  get '/companies' => 'companies#index'
  get '/companies/:id/formulary/' => 'companies#formulary', as: :formulary
  get '/drugs/:id/get_dollar_list' => 'drugs#get_dollar_list', as: :dollar_list
  
  get '/signin'  => 'sessions#new', as: :signin
  post '/signin' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  
  get '/about' => 'static_pages#about'
  
  get '/contact' => 'contact#contact'
  post '/contact' => 'contact#feedback'
  
  get '/insurance' => 'administrators#companies', as: :insurance
  get '/pharmacies' => 'administrators#companies', as: :pharmacies
  get '/administrators/:id' => 'administrators#show', as: :company_plan
  
  post '/companies/:id' => 'companies#add_update'

  post '/drugs' => 'drugs#create'
  post '/drugs/:id' => 'drugs#update'

  delete '/drugs/:id' => 'drugs#destroy'
  delete '/companies/:id' => 'companies#destroy'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
    before_save { email.downcase! }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    
    # Returns the hash digest of the given string.
      def Administrator.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
    before_action :require_login
    before_action :admin_user, only: :destroy
    
    def companies
        @companies = Company.where(co_type: Company.co_types[:insurance]).where.not("name LIKE ?", "%Medicare%")
        @pharmacies = Company.where(co_type: Company.co_types[:pharmacy])
    end
    
    def show
        company = Company.where(name: "#{params[:id].to_s}")[0]
        if !company
            company = Company.find(params[:id])
        end
        if !company
            redirect_to(:root)
        end
        formulary = company.drugs.order("drug_class").order("name")

        respond_to do |format|
            msg = { :status => "ok", :company => company, :formulary => formulary }
            format.json  { render :json => msg } # don't do msg.to_json
        end
    end

    private
     
      def require_login
        unless logged_in?
          flash[:danger] = "You must be logged in to access administration section"
          redirect_to signin_path # halts request cycle
        end
      end
      
    def admin_user
      redirect_to(root_url) unless current_administrator
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.fetch(:company, {}).permit(:name, :url, :plan_year)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/companies.html.haml
.container
  .row
    #admin-name-div.col-md-4
      %h4 Choose a Company to Edit
      #admin-dropdown.dropdown
        %button#admin-button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
          Select Company
          %span.caret
        %ul#admin-dropdown.dropdown-menu
          -companies = ( request.path_info == '/insurance' ? @companies : @pharmacies ) 
          -companies.each do |company|
            %li
              %a{:href=>"javascript:;"}=company.name
          %li.divider
          %li
            %a{:href => "#"} Add Company
    .col-md-8
      %form
        #url-form.form-group
          %label{:for => "companyURL"} Company URL
          %input#companyURL.form-control{:placeholder => "Formulary URL", :type => "url"}/
  .row
    .col-md-12
      #edit.message
      #tablecontent
  #admin-add-row.row
    .col-md-2
      %a{:href => "#"} add new
%hr/
.container
  %div
    =link_to "Log out", logout_path, method: :delete