config/routes.rb
Rails.application.routes.draw do
  resources :companies
  root 'companies#index'
  get '/companies' => 'companies#index'
  get '/companies/:id/formulary/' => 'companies#formulary', as: :formulary
  get '/drugs/:id/get_dollar_list' => 'drugs#get_dollar_list', as: :dollar_list
  
  get '/signin'  => 'sessions#new', as: :signin
  post '/signin' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  
  get '/about' => 'static_pages#about'
  
  get '/contact' => 'contact#contact'
  post '/contact' => 'contact#feedback'
  
  get '/insurance' => 'administrators#companies', as: :insurance
  get '/pharmacies' => 'administrators#companies', as: :pharmacies
  get '/administrators/:id' => 'administrators#show', as: :company_plan
  
  post '/companies/:id' => 'companies#add_update'

  post '/drugs' => 'drugs#create'
  post '/drugs/:id' => 'drugs#update'

  delete '/drugs/:id' => 'drugs#destroy'
  delete '/companies/:id' => 'companies#destroy'

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end

  def feedback
    FeedbackMailer.feedback_email(params[:session]).deliver_later
    flash[:notice] = "Email sent, thank you for the feedback!"
    redirect_to root_path
  end
end

app/views/contact/contact.html.haml
.container.theme-showcase{:role => "main"}
  .container
    .col-md-8
      =form_for(:session, url: contact_path) do |f| {:role => "form"}
        %br{:style => "clear:both"}
        %h3{:style => "margin-bottom: 25px; text-align: center;"} Contact Form
        =f.text_field :name, class: 'form-group form-control', :placeholder => "Name", :required => ""
        =f.email_field :email, class: 'form-group form-control', :placeholder => "Email address", :required => ""
        =f.text_field :subject, class: 'form-group form-control', :placeholder => "Subject", :required => ""
        =f.text_area :message, class: 'form-group form-control', :placeholder => "Message", :required => "", :rows => "10"
        =f.submit "Submit form", class: "btn btn-primary pull-right"