config/routes.rb
Rails.application.routes.draw do
  resources :companies
  root 'companies#index'
  get '/companies' => 'companies#index'
  get '/companies/:id/formulary/' => 'companies#formulary', as: :formulary
  get '/drugs/:id/get_dollar_list' => 'drugs#get_dollar_list', as: :dollar_list
  
  get '/signin'  => 'sessions#new', as: :signin
  post '/signin' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  
  get '/about' => 'static_pages#about'
  
  get '/contact' => 'contact#contact'
  post '/contact' => 'contact#feedback'
  
  get '/insurance' => 'administrators#companies', as: :insurance
  get '/pharmacies' => 'administrators#companies', as: :pharmacies
  get '/administrators/:id' => 'administrators#show', as: :company_plan
  
  post '/companies/:id' => 'companies#add_update'

  post '/drugs' => 'drugs#create'
  post '/drugs/:id' => 'drugs#update'

  delete '/drugs/:id' => 'drugs#destroy'
  delete '/companies/:id' => 'companies#destroy'

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title NCDRINFO
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    #main
      / Fixed navbar
      %nav.navbar.navbar-inverse.navbar-fixed-top
        .container
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => :companies} NC DR INFO
          #navbar.navbar-collapse.collapse
            %ul.nav.navbar-nav
              %li{class: ('active' if request.path_info =~ /(\/companies|^\/$)/)}
                =link_to "Home", companies_path
              -if !request.path_info.match(/(insurance|pharmacies)/)
                %li{class: ('active' if request.path_info == contact_path)}
                  =link_to "Contact", contact_path
                %li{class: ('active' if request.path_info == signin_path)}
                  =link_to "Admin", signin_path
                %li{class: ('active' if request.path_info == about_path)}
                  =link_to "About", about_path
              -else
                %li{class: ('active' if request.path_info == insurance_path)}
                  =link_to "Edit Insurance", insurance_path
                %li{class: ('active' if request.path_info == pharmacies_path)}
                  =link_to "Edit Pharmacies", pharmacies_path
              %li.dropdown
          /.nav-collapse
      -if flash[:notice]
        #notice.alert.alert-success.alert-dismissable
          %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#", :title => "close"} ×
          =flash[:notice]
      -if flash[:warning]
        #notice.alert.alert-warming.alert-dismissable
          %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#", :title => "close"} ×
          =flash[:warning]
      = yield